### ISSUE TITLE
SQLite3 not found error

### ISSUE THREAD

**Issue by chris0030** [codazoda/nolific#7]
When running `php -S localhost:8001` I'm getting the following error on Ubuntu 21.04 with PHP 8.0.8 and SQLite3 3.35.5

```
[Tue Feb  1 08:05:39 2022] PHP 8.0.8 Development Server (http://localhost:8001) started
[Tue Feb  1 08:05:45 2022] 127.0.0.1:45706 Accepted
[Tue Feb  1 08:05:45 2022] 127.0.0.1:45708 Accepted
[Tue Feb  1 08:05:45 2022] PHP Fatal error:  Uncaught Error: Class "SQLite3" not found in /home/chris/Code/nolific/PagesDb.php:4
Stack trace:
#0 /home/chris/Code/nolific/index.php(4): require()
#1 {main}
  thrown in /home/chris/Code/nolific/PagesDb.php on line 4
[Tue Feb  1 08:05:45 2022] 127.0.0.1:45706 [500]: GET / - Uncaught Error: Class "SQLite3" not found in /home/chris/Code/nolific/PagesDb.php:4
Stack trace:
#0 /home/chris/Code/nolific/index.php(4): require()
#1 {main}
  thrown in /home/chris/Code/nolific/PagesDb.php on line 4
[Tue Feb  1 08:05:45 2022] 127.0.0.1:45706 Closing
```
SQLite3 version
```
sqlite3 --version
3.35.5 2021-04-19 18:32:05 1b256d97b553a9611efca188a3d995a2fff712759044ba480f9a0c9e98faalt1
```

PHP version
```
php --version
PHP 8.0.8 (cli) (built: Oct 26 2021 11:42:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies
```

**Comment by chris0030** [comment]
Ahh resolved. Aside from PHP and SQLite3 installed,

I had to install `php8.0-sqlite`

**Comment by codazoda** [comment]
Sounds good, I'll mark this as complete but leave it here as a reference. I wonder if I should add `php7.4-sqlite` to the getting started example or something. I probably need to fire up a debian docker container and an ubuntu docker container and verify the exact packages for each of those before I feel good about the full php install instructions.

**Comment by chris0030** [comment]
Having this run in Docker would be really great, do you have plans to add this? That said I could help if you wanted!

**Comment by codazoda** [comment]
@chris0030 it might be a good idea to create a new issue for Docker, although I'm a little torn on if I should include it.

First, I don't want to complicate the repo with docker setup stuff. Granted it's probably just one docker file and some instructions on how to run it on docker.

Another thought is that Mac OS Monterey removed PHP so it's not included by default in my current everyday machine either. Docker makes sense in this case and it probably make sense on other OS's.

So, as you can see, I'm a little wishy-washy on this, but it's probably a good idea.

**Comment by codazoda** [comment]
On second thought, I do think Docker is a good idea and I've done some initial work to make that happen. This doesn't work yet, because the data needs to move, but I'll fix that.

https://github.com/codazoda/nolific/commit/f916a8277b245ea971bb5f20f3b4640c1e8d07b0

**Comment by codazoda** [comment]
I've now done a full 180 on this idea. I'm running Nolific in Docker myself and, so far, it's amazing. I've even setup my git hooks to automatically destroy and recreate the image and container each time I push new code. See the DOCKER.md file in the current _main_ branch for more information. After I've used it this way for a while I may start pushing the container to Docker Hub and add docker info to the getting started instructions.
